# Generated by Django 4.1.5 on 2023-07-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=20, verbose_name='Hospital Name')),
                ('hospital_contact', models.IntegerField(max_length=10, verbose_name='Contact')),
                ('hospital_address', models.TextField(max_length=50, verbose_name='Address')),
                ('hospital_emailid', models.EmailField(max_length=254)),
                ('hospital_specilization', models.CharField(max_length=200, verbose_name='Hospital Specilization')),
            ],
        ),
    ]
