# Generated by Django 4.1.5 on 2023-07-27 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=50, verbose_name='Doctor Name')),
                ('doctor_specialiazation', models.CharField(max_length=200, verbose_name='Specialiazation')),
                ('doctor_doj', models.DateField(verbose_name='Date of Joining')),
            ],
        ),
    ]
