# Generated by Django 4.1.6 on 2023-08-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('dob', models.DateField(verbose_name='DOB')),
                ('gender', models.CharField(max_length=100, verbose_name='Gender')),
                ('locality', models.CharField(max_length=100, verbose_name='Locality')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('pin', models.IntegerField(verbose_name='Pin')),
                ('state', models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar')], max_length=100, verbose_name='State')),
                ('mobail', models.IntegerField(verbose_name='Mobail')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('job_city', models.CharField(max_length=100, verbose_name='Job City')),
                ('profile_image', models.ImageField(blank=True, upload_to='profileimg', verbose_name='Profile Image')),
                ('my_file', models.FileField(blank=True, upload_to='doc', verbose_name='My File')),
            ],
        ),
    ]
