# Generated by Django 4.1.5 on 2023-06-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=50, verbose_name='Email-id')),
                ('contact', models.IntegerField(max_length=10, verbose_name='Contact')),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
                ('username', models.CharField(max_length=100, verbose_name='Username')),
                ('password', models.CharField(max_length=20, verbose_name='Password')),
            ],
        ),
    ]
