# Generated by Django 4.1.5 on 2023-06-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_alter_userdata_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='contact',
            field=models.IntegerField(max_length=10, verbose_name='Contact'),
        ),
    ]
