# Generated by Django 4.1.6 on 2023-03-13 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=50, verbose_name='Name')),
                ('company_address', models.TimeField(verbose_name='Address')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Status')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Employee ID')),
                ('employee_name', models.CharField(max_length=50, verbose_name='Employee Name')),
                ('employee_contact', models.BigIntegerField(verbose_name='Employee Contact')),
                ('employee_address', models.TextField(verbose_name='Employee Addres')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='')),
                ('is_active', models.BooleanField(default=True, verbose_name='Status')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company', verbose_name='Company ID')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
